version: '3.8'
services:
  email-service:
    build: ./microServices-email
    ports:
      - "3001:3000"
    env_file:
      - ./microServices-email/.env
    depends_on: []

  whatsapp-service:
    build: ./microServices-whatsApp
    ports:
      - "3003:3000"
    env_file:
      - ./microServices-whatsApp/.env
    depends_on: []

  leads-service:
    build: ./microServices-leads
    ports:
      - "3002:3000"
    env_file:
      - ./microServices-leads/.env
    depends_on: []


