version: '3.8'
services:
  email-service:
    build: ./microServices-email
    ports:
      - "3001:3000"
    environment:
      - TOKEN_AIRTABLE=${TOKEN_AIRTABLE}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
    depends_on: []

  whatsapp-service:
    build: ./microServices-whatsApp
    ports:
      - "3003:3002"
    environment:
      - TOKEN_AIRTABLE=${TOKEN_AIRTABLE}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
    depends_on: []

  whatsapp-leads:
    build: ./microServices-leads
    ports:
      - "3004:3005"
    environment:
      - TOKEN_AIRTABLE=${TOKEN_AIRTABLE}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
    depends_on: []


